# Generated by Django 5.2.7 on 2025-10-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cobertura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_agente', models.CharField(max_length=20, unique=True)),
                ('fecha_contratacion', models.DateField()),
                ('especialidad', models.CharField(default='Seguros de Vida', max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'De Vacaciones')], default='activo', max_length=20)),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_oficina', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'db_table': 'univida_agente',
            },
        ),
        migrations.AddField(
            model_name='poliza',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='seguros.agente'),
        ),
    ]
