# Generated by Django 5.2.7 on 2025-10-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0003_factura_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=50, unique=True)),
                ('tipo_siniestro', models.CharField(choices=[('muerte', 'Muerte'), ('invalidez', 'Invalidez Total'), ('enfermedad', 'Enfermedad Grave'), ('otros', 'Otros')], max_length=20)),
                ('fecha_siniestro', models.DateField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('monto_reclamado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='reportado', max_length=20)),
                ('documentos_adjuntos', models.TextField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='seguros.poliza')),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
                'db_table': 'univida_siniestro',
            },
        ),
    ]
