# Generated by Django 5.2.7 on 2025-10-27 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0004_siniestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo_nota', models.CharField(choices=[('general', 'General'), ('seguimiento', 'Seguimiento'), ('recordatorio', 'Recordatorio'), ('importante', 'Importante')], default='general', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='seguros.poliza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Póliza',
                'verbose_name_plural': 'Notas de Póliza',
                'db_table': 'univida_nota_poliza',
            },
        ),
    ]
