# Generated by Django 5.2.7 on 2025-10-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0006_rol_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('AGENTE', 'Agente'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10),
        ),
    ]
