# Generated by Django 5.2.7 on 2025-10-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
