# Generated by Django 5.2.7 on 2025-10-29 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0008_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL),
        ),
    ]
