# Generated by Django 5.2.7 on 2025-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0009_alter_agente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_agente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_cliente',
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
