# Generated by Django 5.2.7 on 2025-11-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0010_remove_usuario_es_agente_remove_usuario_es_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='prima_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('cotizacion', 'En Cotización'), ('activa', 'Activa'), ('inactiva', 'Inactiva'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='cotizacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='tipo_siniestro',
            field=models.CharField(choices=[('muerte', 'Muerte'), ('invalidez', 'Invalidez Total'), ('invalidez_parcial', 'Invalidez Parcial'), ('gastos_medicos', 'Gastos Médicos'), ('hospitalizacion', 'Hospitalización'), ('incapacidad_temporal', 'Incapacidad Temporal'), ('otros', 'Otros')], max_length=20),
        ),
    ]
