# Generated by Django 5.2.7 on 2025-12-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0011_poliza_prima_mensual_alter_poliza_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Carnet de Identidad'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nombre_completo',
            field=models.CharField(max_length=100),
        ),
    ]
