# Generated by Django 5.2.7 on 2025-12-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0012_beneficiario_ci_beneficiario_materno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterField(
            model_name='factura',
            name='concepto',
            field=models.CharField(default='Prima de seguro', max_length=255),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('cotizacion', 'En Cotización'), ('pendiente_pago', 'Pendiente de Pago'), ('activa', 'Activa'), ('inactiva', 'Inactiva'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='cotizacion', max_length=20),
        ),
        migrations.AlterModelTable(
            name='factura',
            table=None,
        ),
    ]
