# Generated by Django 5.2.7 on 2025-12-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0013_alter_factura_options_alter_factura_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('cotizacion', 'En Cotización'), ('pendiente_pago', 'Pendiente de Pago'), ('activa', 'Activa'), ('inactiva', 'Inactiva'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], default='cotizacion', max_length=20),
        ),
    ]
