# Generated by Django 5.2.7 on 2025-12-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0014_alter_poliza_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to='seguros.agente'),
        ),
    ]
